name: vigia
description: "Aplicativo de logística e monitoramento Vigia."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # --- GERENCIAMENTO DE ESTADO E TEMAS ---
  provider: ^6.1.1

  # --- RESPONSIVIDADE ---
  flutter_screenutil: ^5.9.3

  # --- INTERFACE E GRÁFICOS ---
  google_fonts: ^6.1.0
  fl_chart: ^0.69.0

  # --- MAPAS E NAVEGAÇÃO ---
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo_vigia.png